// <auto-generated />
using System;
using D2ST.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D2ST.Persistence.Migrations
{
    [DbContext(typeof(D2stDbContext))]
    partial class D2stDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("D2ST.Persistence.AccountEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("PersonaName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("D2ST.Persistence.DotaPlusAccountEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PlusFlags")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SteamAgreementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("DotaPlusAccounts");
                });

            modelBuilder.Entity("D2ST.Persistence.DotaPlusTransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<uint>("ChangedByAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Days")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAtAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CreatedAt");

                    b.ToTable("DotaPlusTransactions");
                });

            modelBuilder.Entity("D2ST.Persistence.EconItemEntity", b =>
                {
                    b.Property<ulong>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("DefIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquippedStatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Inventory")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Style")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("AccountId", "DefIndex")
                        .IsUnique();

                    b.ToTable("EconItems");
                });

            modelBuilder.Entity("D2ST.Persistence.FriendRequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("FromAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ToAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromAccountId", "Status");

                    b.HasIndex("ToAccountId", "Status");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("D2ST.Persistence.FriendshipEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FriendAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "FriendAccountId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("D2ST.Persistence.LeaderboardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortMethod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("Leaderboards");
                });

            modelBuilder.Entity("D2ST.Persistence.LeaderboardEntryEntity", b =>
                {
                    b.Property<int>("LeaderboardId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UgcHandle")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LeaderboardId", "AccountId");

                    b.ToTable("LeaderboardEntries");
                });

            modelBuilder.Entity("D2ST.Persistence.MatchEntity", b =>
                {
                    b.Property<ulong>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutomaticSurrender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageNetworthDelta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarracksStatusJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Cluster")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DireScore")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("EventScore")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FirstBloodTime")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GoodGuysWin")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LobbyId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MatchFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("PreGameDuration")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("RadiantScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ServerVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TowerStatusJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.HasIndex("EndedAt");

                    b.HasIndex("LobbyId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("D2ST.Persistence.MatchPlayerEntity", b =>
                {
                    b.Property<ulong>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClaimedDenies")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClaimedFarmGold")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ClaimedMisses")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Denies")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HeroPickOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HeroWasRandomed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemPurchaseTimesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Lane")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LastHits")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LeaverStatus")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MatchPlayerFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Misses")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PartyId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ScaledHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ScaledHeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ScaledTowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SupportAbilityValue")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SupportGold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TimeLastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("XpPerMinute")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("D2ST.Persistence.PlayerHeroStatsEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastMatchAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAssists")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDenies")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalHeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalKills")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalLastHits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalXpPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "HeroId");

                    b.HasIndex("AccountId");

                    b.ToTable("PlayerHeroStats");
                });

            modelBuilder.Entity("D2ST.Persistence.PlayerProfileStatsEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastMatchAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaverCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAssists")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDenies")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGoldPerMin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalGoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalHeroHealing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalKills")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalLastHits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPlayTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTowerDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalXpPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("PlayerProfileStats");
                });

            modelBuilder.Entity("D2ST.Persistence.PlayerRankEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCalibrated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mmr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("PlayerRanks");
                });

            modelBuilder.Entity("D2ST.Persistence.ProfileCardEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("ProfileCards");
                });

            modelBuilder.Entity("D2ST.Persistence.RemoteStorageFileEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SyncPlatforms")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "FileName");

                    b.ToTable("RemoteStorageFiles");
                });

            modelBuilder.Entity("D2ST.Persistence.ShowcaseEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ShowcaseType")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "ShowcaseType");

                    b.ToTable("Showcases");
                });

            modelBuilder.Entity("D2ST.Persistence.StoreCatalogComponentEntity", b =>
                {
                    b.Property<uint>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ComponentProductId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "ComponentProductId");

                    b.ToTable("StoreCatalogComponents");
                });

            modelBuilder.Entity("D2ST.Persistence.StoreCatalogItemEntity", b =>
                {
                    b.Property<uint>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BuildVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DefIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("PriceCredits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("Active", "ProductType");

                    b.ToTable("StoreCatalogItems");
                });

            modelBuilder.Entity("D2ST.Persistence.StorePurchaseTransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCredits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("StorePurchaseTransactions");
                });

            modelBuilder.Entity("D2ST.Persistence.UserAchievementEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Earned")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxProgress")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Progress")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "Name");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("D2ST.Persistence.UserStatEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Data")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "Name");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("D2ST.Persistence.WalletEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceCredits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedCredits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("D2ST.Persistence.WalletTransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountCredits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BalanceAfterCredits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("AccountId", "CreatedAt");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("D2ST.Persistence.WorkshopItemEntity", b =>
                {
                    b.Property<ulong>("PublishedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptedForUse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ConsumerAppId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CreatorAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerSteamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<uint>("TimeCreated")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TimeUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalFilesSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("VotesDown")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("VotesUp")
                        .HasColumnType("INTEGER");

                    b.HasKey("PublishedFileId");

                    b.ToTable("WorkshopItems");
                });

            modelBuilder.Entity("D2ST.Persistence.WorkshopSubscriptionEntity", b =>
                {
                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("PublishedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisabledLocally")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SubscribedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "PublishedFileId");

                    b.ToTable("WorkshopSubscriptions");
                });

            modelBuilder.Entity("D2ST.Persistence.MatchPlayerEntity", b =>
                {
                    b.HasOne("D2ST.Persistence.MatchEntity", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("D2ST.Persistence.MatchEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
